### ISSUE TITLE
训练报错，拉取SambertHifigan语音合成-多语言-多人预训练-16k多语言模型后，用kantts的sambert这部分训练会报错

### ISSUE THREAD

**Issue by wukongbuku** [AlibabaResearch/KAN-TTS#94]
环境啥的都没问题，用那个中文多人预训练就没问题
先简单说一下报错信息（这个sy参数在对应的配置文件中也存在）

  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 716, in __init__
    self.text_encoder = TextFftEncoder(config)
  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 268, in __init__
    nb_ling_sy = config["sy"]
KeyError: 'sy'

报错全部信息
(sambert_train) weipeng@beta88:/mnt1/wp/Git_Code/KAN-TTS$ CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --use_env /mnt1/wp/Git_Code/KAN-TTS/kantts/bin/train_sambert.py --model_config /mnt1/wp/damo_download/sambert_pretrain/speech_sambert-hifigan_tts_multilingual_multisp_pretrain_16k/basemodel_16k/sambert/config.yaml --resume_path /mnt1/wp/damo_download/sambert_pretrain/speech_sambert-hifigan_tts_multilingual_multisp_pretrain_16k/basemodel_16k/sambert/ckpt/checkpoint_1000000.pth  --root_dir /mnt1/wp/Git_Code/KAN-TTS/training_stage/huiben_en_v11_v11_feats --stage_dir /mnt1/wp/Git_Code/KAN-TTS/training_stage/011-huiben_en_sambert_ckpt-v11  
/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
2024-02-26:16:05:22 INFO [train_sambert.py:51] Args local rank: 0
2024-02-26:16:05:22 INFO [train_sambert.py:82] audio_config = {'fmax': 8000.0, 'fmin': 0.0, 'hop_length': 200, 'max_norm': 1.0, 'min_level_db': -100.0, 'n_fft': 2048, 'n_mels': 80, 'norm_type': 'mean_std', 'num_workers': 16, 'phone_level_feature': True, 'preemphasize': False, 'ref_level_db': 20, 'sampling_rate': 16000, 'symmetric': False, 'trim_silence': True, 'trim_silence_threshold_db': 60, 'wav_normalize': True, 'win_length': 1000}
2024-02-26:16:05:22 INFO [train_sambert.py:82] create_time = 2024-02-26 16:05:22
2024-02-26:16:05:22 INFO [train_sambert.py:82] git_revision_hash = 66202d052189a3dcca5f75c718c47a7a5cc68116
2024-02-26:16:05:22 INFO [train_sambert.py:82] Loss = {'AttentionBinarizationLoss': {'enable': True, 'params': {'start_epoch': 0, 'warmup_epoch': 100}}, 'AttentionCTCLoss': {'enable': True}, 'MelReconLoss': {'enable': True, 'params': {'loss_type': 'mae'}}, 'ProsodyReconLoss': {'enable': True, 'params': {'loss_type': 'mae'}}}
2024-02-26:16:05:22 INFO [train_sambert.py:82] Model = {'KanTtsSAMBERT': {'optimizer': {'params': {'betas': [0.9, 0.98], 'eps': 1e-09, 'lr': 0.001, 'weight_decay': 0.0}, 'type': 'Adam'}, 'params': {'MAS': True, 'decoder_attention_dropout': 0.1, 'decoder_dropout': 0.1, 'decoder_ffn_inner_dim': 1024, 'decoder_num_heads': 8, 'decoder_num_layers': 12, 'decoder_num_units': 128, 'decoder_prenet_units': [256, 256], 'decoder_relu_dropout': 0.1, 'dur_pred_lstm_units': 128, 'dur_pred_prenet_units': [128, 128], 'embedding_dim': 512, 'emotion_units': 32, 'encoder_attention_dropout': 0.1, 'encoder_dropout': 0.1, 'encoder_ffn_inner_dim': 1024, 'encoder_num_heads': 8, 'encoder_num_layers': 8, 'encoder_num_units': 128, 'encoder_projection_units': 32, 'encoder_relu_dropout': 0.1, 'max_len': 800, 'multilingual': True, 'num_mels': 80, 'outputs_per_step': 3, 'postnet_dropout': 0.1, 'postnet_ffn_inner_dim': 512, 'postnet_filter_size': 41, 'postnet_fsmn_num_layers': 4, 'postnet_lstm_units': 128, 'postnet_num_memory_units': 256, 'postnet_shift': 17, 'predictor_dropout': 0.1, 'predictor_ffn_inner_dim': 256, 'predictor_filter_size': 41, 'predictor_fsmn_num_layers': 3, 'predictor_lstm_units': 128, 'predictor_num_memory_units': 128, 'predictor_shift': 0, 'speaker_units': 32}, 'scheduler': {'params': {'warmup_steps': 4000}, 'type': 'NoamLR'}}}
2024-02-26:16:05:22 INFO [train_sambert.py:82] allow_cache = False
2024-02-26:16:05:22 INFO [train_sambert.py:82] batch_size = 8
2024-02-26:16:05:22 INFO [train_sambert.py:82] eval_interval_steps = 5000
2024-02-26:16:05:22 INFO [train_sambert.py:82] grad_norm = 1.0
2024-02-26:16:05:22 INFO [train_sambert.py:82] linguistic_unit = {'cleaners': 'english_cleaners', 'language': '11lang', 'lfeat_type_list': 'language_specified,byte_index,sy,tone,syllable_flag,word_segment,emo_category,speaker_category', 'speaker_list': 'zhcnf1,zhcnf2,zhcnm1,enusf1,enusf2,enusm1,kokrf1,kokrf2,engbf1,engbm1,yuehkf1,yuehkf2,jajpf1,jajpf2,jajpm1,dedef1,dedem1,frfrf1,frfrm1,ititf1,ititm1,esesf1,esesm1,ruruf1,rurum1'}
2024-02-26:16:05:22 INFO [train_sambert.py:82] log_interval_steps = 1000
2024-02-26:16:05:22 INFO [train_sambert.py:82] model_type = sambert
2024-02-26:16:05:22 INFO [train_sambert.py:82] num_save_intermediate_results = 4
2024-02-26:16:05:22 INFO [train_sambert.py:82] num_workers = 4
2024-02-26:16:05:22 INFO [train_sambert.py:82] pin_memory = False
2024-02-26:16:05:22 INFO [train_sambert.py:82] remove_short_samples = False
2024-02-26:16:05:22 INFO [train_sambert.py:82] save_interval_steps = 5000
2024-02-26:16:05:22 INFO [train_sambert.py:82] train_max_steps = 1100001
2024-02-26:16:05:22 INFO [dataset.py:572] Loading metafile...
100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 45756.04it/s]
2024-02-26:16:05:22 ERROR [lang_symbols.py:78] Language 11lang not supported. Using PinYin as default
2024-02-26:16:05:22 INFO [dataset.py:572] Loading metafile...
100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 36157.79it/s]
2024-02-26:16:05:22 ERROR [lang_symbols.py:78] Language 11lang not supported. Using PinYin as default
2024-02-26:16:05:22 INFO [train_sambert.py:108] The number of training files = 3.
2024-02-26:16:05:22 INFO [train_sambert.py:109] The number of validation files = 2.
Traceback (most recent call last):
  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/bin/train_sambert.py", line 237, in <module>
    train(
  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/bin/train_sambert.py", line 150, in train
    model, optimizer, scheduler = model_builder(config, device, local_rank, distributed)
  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/models/__init__.py", line 163, in model_builder
    model, optimizer, scheduler = builder_func(config, device, rank, distributed)
  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/models/__init__.py", line 95, in sambert_model_builder
    model["KanTtsSAMBERT"] = KanTtsSAMBERT(
  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 716, in __init__
    self.text_encoder = TextFftEncoder(config)
  File "/mnt1/wp/Git_Code/KAN-TTS/kantts/models/sambert/kantts_sambert.py", line 268, in __init__
    nb_ling_sy = config["sy"]
KeyError: 'sy'
[2024-02-26 16:05:25,537] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2904611) of binary: /home/weipeng/miniconda3/envs/sambert_train/bin/python
Traceback (most recent call last):
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/weipeng/miniconda3/envs/sambert_train/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt1/wp/Git_Code/KAN-TTS/kantts/bin/train_sambert.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-26_16:05:25
  host      : beta88
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2904611)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by wukongbuku** [comment]
官方恢复了，这个多语言模型还在集成中
